### PR TITLE
Fixed include order in config

### PR DESCRIPTION
**Pull request by dsayson403**
The backgrounds sometimes depend on the region setting defined in the style.

### CODE REVIEW

**Comment by s1eve-mcdichae1** [comment]
This breaks `nes_simple_*` styles with certain backgrounds.

Previously, `<selectedColor>ffffff</selectedColor>` in `nes_simple.xml` would overwrite whatever custom color had been set in the selected background's `.xml`. With this change it's the other way around, and the background's custom color is overwriting the white.

Depending on the chosen background, this may be low-contrast or, as in the case of `neon_purple.xml`, literally the same color as the selector bar!

    <selectorColor>00dbff</selectorColor>
    <selectedColor>00dbff</selectedColor>




The `nes_rich_*` and `snes_*` styles don't have this problem. Not sure yet what they're doing differently to make it work:

**Comment by dsayson403** [comment]
Well, it appears that getting the backgrounds to show the US versions of the systems was not as easy as I originally thought. Good job on finding this issue. I will close this pull request since addressing this problem requires a different approach.

**Comment by s1eve-mcdichae1** [comment]
@dvsayson by darkening the image `style/nes_simple/selector_bar${wide}.png` to a neutral grey, the contrast is markedly improved:

**Comment by dsayson403** [comment]
@s1eve-mcdichae1 I created another pull request (#28) with a proposed fix that shouldn't mess with the colors like this one does.

**Pull request closed without merging**
